apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: trader-peer0
  namespace: trader-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: trader-peer0
  chart:
    git: git@github.com:saronmarinelle/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/peernode    
  values:
    metadata:
      namespace: trader-net
      images:
        couchdb: couchdb:3.1
        peer: hyperledger/fabric-peer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
        
    peer:
      name: peer0
      gossippeeraddress: peer0.trader-net:7051
      gossipexternalendpoint: peer0.trader-net:7051
      localmspid: traderMSP
      loglevel: info
      tlsstatus: true
      builder: hyperledger/fabric-ccenv:2.2.2
      couchdb:
        username: trader-user

    storage:
      peer:
        storageclassname: tradersc
        storagesize: 512Mi
      couchdb:
        storageclassname: tradersc
        storagesize: 1Gi

    vault:
      role: vault-role
      address: http://afa8761a6902d4eed83106ebd15d7aec-1934446345.ap-southeast-1.elb.amazonaws.com:8200
      authpath: devtrader-net-auth
      secretprefix: secretsv2/data/crypto/peerOrganizations/trader-net/peers/peer0.trader-net
      secretambassador: secretsv2/data/crypto/peerOrganizations/trader-net/ambassador
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretcouchdbpass: secretsv2/data/credentials/trader-net/couchdb/trader?user

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7051
        events:
          clusteripport: 7053
        couchdb:
          clusteripport: 5984
          
    proxy:
      provider: "none"
      external_url_suffix: develop.local.com

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
