apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychain-orderer1
  namespace: supplychain-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: supplychain-orderer1
  chart:
    git: git@github.com:saronmarinelle/bevel.git
    ref: local
    path: platforms/hyperledger-fabric/charts/orderernode
  values:
    metadata:
      namespace: supplychain-net
      images:
        orderer: hyperledger/fabric-orderer:2.2.2
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    annotations:  
      service:
        - example1: example2
      pvc:
      deployment:
    orderer:
      name: orderer1
      loglevel: info
      localmspid: supplychainMSP
      tlsstatus: true
      keepaliveserverinterval: 10s
    
    consensus:
      name: raft

    storage:
      storageclassname: supplychainsc
      storagesize: 512Mi  

    service:
      servicetype: ClusterIP
      ports:
        grpc:
          clusteripport: 7050

    vault:
      address: http://afa8761a6902d4eed83106ebd15d7aec-1934446345.ap-southeast-1.elb.amazonaws.com:8200
      role: vault-role
      authpath: devsupplychain-net-auth
      secretprefix: secretsv2/data/crypto/ordererOrganizations/supplychain-net/orderers/orderer1.supplychain-net
      imagesecretname: regcred
      serviceaccountname: vault-auth

    proxy:
      provider: none
      external_url_suffix: develop.local.com

    genesis: |-
      CiIaIMOkKKQeesAwN+8Yau9J5epjH8qy1LdF05XMP8qfbaMnEo9dCoxdColdCngKWggBEAEaBgiY
      q+qWBiIKc3lzY2hhbm5lbCpAOTdkNDFiMjU3ZjA4MjA4NzE3YzM1OWUyODZlMjFlYjM3NWMyNzEx
      NDEyOTdkNzM4OGEyN2EyNjRkNjFjNzQxZRIaEhgLoIbA7XDzdGFDQGnPCrSUyhVKH7jFiWkSjFwK
      iVwShlwSkSsKB09yZGVyZXIShSsSyhYKDnN1cHBseWNoYWluTVNQErcWGsMUCgNNU1ASuxQSsBQS
      rRQKDnN1cHBseWNoYWluTVNQEvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBREND
      QWFhZ0F3SUJBZ0lVSWlCQjJxSjdzNTJyWWx2cVdJek9mVmQ3V09vd0NnWUlLb1pJemowRUF3SXcK
      WGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dU
      Rzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpqWVM1emRYQndi
      SGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeU1URTBOalV4V2hjTk1qVXdOVEV4TVRFME5qVXhX
      akJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3RFFZRFZRUUhE
      QVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1NRW1OaExuTjFj
      SEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VIQTBJQUJDcjhu
      ODlTMHRNM2xUTG5vdTEyYTVJVkNjQzBNd2orVCt6empvanNreDBRR3NBVXM4MU0KZDJVUE1uSEVk
      a2xaV3Y1U0lQdW8rVi9YaGZ3S0pEUHlJM2FqUWpCQU1BOEdBMVVkRXdFQi93UUZNQU1CQWY4dwpE
      Z1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUdPZ3Q0Qi8yL0ZaMCs2cGVrREZjNW9D
      RlA0ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCSnR6b2c0WVArQzlrcExCa2ZUR3hUTVJvcUJz
      N2hqTlRobncrbzQxOTAKcXdJaEFQdjRkQVA2V2hjMldYTkl6bG1WOHpEREZIelJub1NrU3A2b3Vx
      TEpVRmJZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIqIILS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUM0VENDQW9pZ0F3SUJBZ0lVVklId1pMUHRQZlBkWERaMC9BR3NsbHM1RUdJd0Nn
      WUlLb1pJemowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJq
      RVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZR
      UUREQkpqWVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeU1URTFOVEF3V2hjTk1q
      TXdOekl5TVRJd01EQXdXakJzTVFzd0NRWURWUVFHRXdKSFFqRWIKTUJrR0ExVUVCeE1TTlRFdU5U
      QXZMVEF1TVRNdlRHOXVaRzl1TVJBd0RnWURWUVFLRXdkUGNtUmxjbVZ5TVE0dwpEQVlEVlFRTEV3
      VmhaRzFwYmpFZU1Cd0dBMVVFQXd3VlFXUnRhVzVBYzNWd2NHeDVZMmhoYVc0dGJtVjBNRmt3CkV3
      WUhLb1pJemowQ0FRWUlLb1pJemowREFRY0RRZ0FFK3RhdWlBVmU3VXlLMnRybUlxbEY4UVE4K202
      akVjRUEKOFZ2aWViWkxEY09nYkU0Y2ordXl1ZkxGT1Ayd1c5TUo4bVVmUnl3azR2TTNqdzhEeDR2
      K3ZLT0NBUlF3Z2dFUQpNQTRHQTFVZER3RUIvd1FFQXdJSGdEQU1CZ05WSFJNQkFmOEVBakFBTUIw
      R0ExVWREZ1FXQkJUMWp5cFhCR2xGCnRpOU41bTFwQ1FEWXlKR3lkREFmQmdOVkhTTUVHREFXZ0JR
      R09ndDRCLzIvRlowKzZwZWtERmM1b0NGUDR6QWsKQmdOVkhSRUVIVEFiZ2hsallTMTBiMjlzY3kw
      MllqYzNORFUxWkRaaUxXWTNPSEZ1TUlHSkJnZ3FBd1FGQmdjSQpBUVI5ZXlKaGRIUnljeUk2ZXlK
      aFltRmpMbWx1YVhRaU9pSjBjblZsSWl3aVlXUnRhVzRpT2lKMGNuVmxJaXdpCmFHWXVRV1ptYVd4
      cFlYUnBiMjRpT2lJaUxDSm9aaTVGYm5KdmJHeHRaVzUwU1VRaU9pSkJaRzFwYmtCemRYQncKYkhs
      amFHRnBiaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpqMEVBd0lE
      UndBdwpSQUlnSTJOeEtnVGRsOWdrZ2dQU0VJSXRoR2tURFdHdmlpMjhWNk5vZzNHUkhpNENJRDNE
      aE9YU3BkOXh6L1ZrCmpDMjJlUVpWWW9LSGlNNXEwNXJWQnVldU5yRTkKLS0tLS1FTkQgQ0VSVElG
      SUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SvEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t
      Ck1JSUNBRENDQWFhZ0F3SUJBZ0lVSWlCQjJxSjdzNTJyWWx2cVdJek9mVmQ3V09vd0NnWUlLb1pJ
      emowRUF3SXcKWGpFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBH
      QTFVRUJ3d0dURzl1Wkc5dQpNUkF3RGdZRFZRUUtEQWRQY21SbGNtVnlNUnN3R1FZRFZRUUREQkpq
      WVM1emRYQndiSGxqYUdGcGJpMXVaWFF3CkhoY05Nakl3TnpJeU1URTBOalV4V2hjTk1qVXdOVEV4
      TVRFME5qVXhXakJlTVFzd0NRWURWUVFHRXdKSFFqRVAKTUEwR0ExVUVDQXdHVEc5dVpHOXVNUTh3
      RFFZRFZRUUhEQVpNYjI1a2IyNHhFREFPQmdOVkJBb01CMDl5WkdWeQpaWEl4R3pBWkJnTlZCQU1N
      RW1OaExuTjFjSEJzZVdOb1lXbHVMVzVsZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHClNNNDlBd0VI
      QTBJQUJDcjhuODlTMHRNM2xUTG5vdTEyYTVJVkNjQzBNd2orVCt6empvanNreDBRR3NBVXM4MU0K
      ZDJVUE1uSEVka2xaV3Y1U0lQdW8rVi9YaGZ3S0pEUHlJM2FqUWpCQU1BOEdBMVVkRXdFQi93UUZN
      QU1CQWY4dwpEZ1lEVlIwUEFRSC9CQVFEQWdHbU1CMEdBMVVkRGdRV0JCUUdPZ3Q0Qi8yL0ZaMCs2
      cGVrREZjNW9DRlA0ekFLCkJnZ3Foa2pPUFFRREFnTklBREJGQWlCSnR6b2c0WVArQzlrcExCa2ZU
      R3hUTVJvcUJzN2hqTlRobncrbzQxOTAKcXdJaEFQdjRkQVA2V2hjMldYTkl6bG1WOHpEREZIelJu
      b1NrU3A2b3VxTEpVRmJZCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KGgZBZG1pbnMiOAoGQWRt
      aW5zEi4SJAgBEiASCBIGCAESAggAGhQSEgoOc3VwcGx5Y2hhaW5NU1AQARoGQWRtaW5zIjsKC0Vu
      ZG9yc2VtZW50EiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdSZWFkZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyI3
      CgdXcml0ZXJzEiwSIggBEh4SCBIGCAESAggAGhISEAoOc3VwcGx5Y2hhaW5NU1AaBkFkbWlucyoG
      QWRtaW5zGiIKCUJhdGNoU2l6ZRIVEgsIChCAgIAxGICAQBoGQWRtaW5zGh4KDEJhdGNoVGltZW91
      dBIOEgQKAjJzGgZBZG1pbnMaHwoTQ2hhbm5lbFJlc3RyaWN0aW9ucxIIGgZBZG1pbnMaJAoMQ2Fw
      YWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucxqKEgoNQ29uc2Vuc3VzVHlwZRL4ERLtEQoI
      ZXRjZHJhZnQS4BEKyREKGG9yZGVyZXIxLnN1cHBseWNoYWluLW5ldBCKNxrTCC0tLS0tQkVHSU4g
      Q0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdBd0lCQWdJVVNBYXJNejFnMWRhNlRaemJSN0t4
      dUh3VFY0WXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdN
      Qmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpHOXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5
      TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFHRnBiaTF1WlhRdwpIaGNOTWpJd056SXlNVEUx
      TlRBd1doY05Nak13TnpJeU1USXdNREF3V2pCeE1Rc3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVF
      QnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1SQXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcK
      RGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZRUURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGph
      R0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVJLVnovSmhjT2Jm
      eFA0cW9LMkYzVkVyQmFrCk04dUFTWG5vTncrL1lMeERoRE1LREVqbk9jS1NXR0NFbUNqL3ZtZDY3
      Y05LT25iU2VFVjFzOFc1ZmQ4Q280SUIKTURDQ0FTd3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdB
      MVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFN
      QjBHQTFVZERnUVdCQlJXMmpEazNpNjA1MnpQS3A5Q0F5V2hqREk0CllqQWZCZ05WSFNNRUdEQVdn
      QlFHT2d0NEIvMi9GWjArNnBla0RGYzVvQ0ZQNHpBL0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlN
      UzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdWeVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZ
      Mjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhKeklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlq
      b2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpvaWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFX
      NHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdWeVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNB
      QXdSUUloQU9aR3VVKzNUenUrcmhuKwo1ZjFpbUdWTjJHamdkb0xxUlMwMjVUbzNEMXlZQWlCVWJj
      dlZ3MUlvemwrdE1kZEhtQnZjOStnY1duekk2U3ZXCjM5ZFBMTW40aUE9PQotLS0tLUVORCBDRVJU
      SUZJQ0FURS0tLS0tCiLTCC0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEQXpDQ0FxbWdB
      d0lCQWdJVVNBYXJNejFnMWRhNlRaemJSN0t4dUh3VFY0WXdDZ1lJS29aSXpqMEVBd0l3ClhqRUxN
      QWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0ExVUVCd3dHVEc5dVpH
      OXUKTVJBd0RnWURWUVFLREFkUGNtUmxjbVZ5TVJzd0dRWURWUVFEREJKallTNXpkWEJ3YkhsamFH
      RnBiaTF1WlhRdwpIaGNOTWpJd056SXlNVEUxTlRBd1doY05Nak13TnpJeU1USXdNREF3V2pCeE1R
      c3dDUVlEVlFRR0V3SkhRakViCk1Ca0dBMVVFQnhNU05URXVOVEF2TFRBdU1UTXZURzl1Wkc5dU1S
      QXdEZ1lEVlFRS0V3ZFBjbVJsY21WeU1SQXcKRGdZRFZRUUxFd2R2Y21SbGNtVnlNU0V3SHdZRFZR
      UURFeGh2Y21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdQpaWFF3V1RBVEJnY3Foa2pPUFFJQkJn
      Z3Foa2pPUFFNQkJ3TkNBQVJLVnovSmhjT2JmeFA0cW9LMkYzVkVyQmFrCk04dUFTWG5vTncrL1lM
      eERoRE1LREVqbk9jS1NXR0NFbUNqL3ZtZDY3Y05LT25iU2VFVjFzOFc1ZmQ4Q280SUIKTURDQ0FT
      d3dEZ1lEVlIwUEFRSC9CQVFEQWdPb01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdF
      RgpCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlJXMmpEazNpNjA1MnpQS3A5
      Q0F5V2hqREk0CllqQWZCZ05WSFNNRUdEQVdnQlFHT2d0NEIvMi9GWjArNnBla0RGYzVvQ0ZQNHpB
      L0JnTlZIUkVFT0RBMmdoaHYKY21SbGNtVnlNUzV6ZFhCd2JIbGphR0ZwYmkxdVpYU0NHbTl5WkdW
      eVpYSXhMbVJsZG1Wc2IzQXViRzlqWVd3dQpZMjl0TUd3R0NDb0RCQVVHQndnQkJHQjdJbUYwZEhK
      eklqcDdJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2lJaXdpCmFHWXVSVzV5YjJ4c2JXVnVkRWxFSWpv
      aWIzSmtaWEpsY2pFdWMzVndjR3g1WTJoaGFXNHRibVYwSWl3aWFHWXUKVkhsd1pTSTZJbTl5WkdW
      eVpYSWlmWDB3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUloQU9aR3VVKzNUenUrcmhuKwo1ZjFpbUdW
      TjJHamdkb0xxUlMwMjVUbzNEMXlZQWlCVWJjdlZ3MUlvemwrdE1kZEhtQnZjOStnY1duekk2U3ZX
      CjM5ZFBMTW40aUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tChISCgU1MDBtcxAKGAEgBSiA
      gIAIGgZBZG1pbnMiIgoHV3JpdGVycxIXEg0IAxIJCgdXcml0ZXJzGgZBZG1pbnMiIgoGQWRtaW5z
      EhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiKgoPQmxvY2tWYWxpZGF0aW9uEhcSDQgDEgkKB1dy
      aXRlcnMaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyoGQWRtaW5z
      Eq4uCgtDb25zb3J0aXVtcxKeLhLTLQoVU3VwcGx5Q2hhaW5Db25zb3J0aXVtErktEpAWCgl0cmFk
      ZXJNU1ASghYaohQKA01TUBKaFBKPFBKMFAoJdHJhZGVyTVNQEuEFLS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUI5RENDQVpxZ0F3SUJBZ0lVS1BTWG1JOFh1SEJ6RGVUaTdXTTJ0dE5RYmpN
      d0NnWUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21s
      amFERVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUTh3RFFZRFZRUUtEQVpVY21Ga1pYSXhGakFVQmdO
      VkJBTU1EV05oTG5SeVlXUmxjaTF1WlhRd0hoY05Nakl3Ck56SXlNVEUwT0RVMFdoY05NalV3TlRF
      eE1URTBPRFUwV2pCWU1Rc3dDUVlEVlFRR0V3SkRTREVQTUEwR0ExVUUKQ0F3R1duVnlhV05vTVE4
      d0RRWURWUVFIREFaYWRYSnBZMmd4RHpBTkJnTlZCQW9NQmxSeVlXUmxjakVXTUJRRwpBMVVFQXd3
      TlkyRXVkSEpoWkdWeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTDFU
      CkZFMW0wRGpzT3YydkU1OXQvQzhCTWhKVnNvUE1mdGZyV2tWM2RCWnhLVHArQ1VsSm5JSGc1aFdo
      ZkRxR3JORTQKMmFZMjArTVNVdFVER2ZnZUNlS2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3
      RGdZRFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJUMHJ6cm1lSitoL1hacDA4N0FCcWdz
      bndBQ3BUQUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUVBMy9uMnRrZEo0NVRmc21xcFREUzZGaVZs
      VnFJUnhUekI3ZUxiSHRiOGU2SUNJSFVPMCt0cGZ5aWUKUTg3aHl3d08rVHc4WVVaeFZrbDA4RGx0
      OGNlYlBITTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoipggtLS0tLUJFR0lOIENFUlRJRklD
      QVRFLS0tLS0KTUlJQzVEQ0NBb3VnQXdJQkFnSVVBU1BaZnZCTmhVYm1CZ2NMVWF5eEorTUovZ293
      Q2dZSUtvWkl6ajBFQXdJdwpXREVMTUFrR0ExVUVCaE1DUTBneER6QU5CZ05WQkFnTUJscDFjbWxq
      YURFUE1BMEdBMVVFQnd3R1duVnlhV05vCk1ROHdEUVlEVlFRS0RBWlVjbUZrWlhJeEZqQVVCZ05W
      QkFNTURXTmhMblJ5WVdSbGNpMXVaWFF3SGhjTk1qSXcKTnpJeU1URTFOekF3V2hjTk1qTXdOekl5
      TVRJd01qQXdXakIwTVFzd0NRWURWUVFHRXdKRFNERWFNQmdHQTFVRQpCeE1STkRjdU16Z3ZPQzQx
      TkM5YWRYSnBZMmd4RHpBTkJnTlZCQW9UQmxSeVlXUmxjakVkTUF3R0ExVUVDeE1GCllXUnRhVzR3
      RFFZRFZRUUxFd1owY21Ga1pYSXhHVEFYQmdOVkJBTU1FRUZrYldsdVFIUnlZV1JsY2kxdVpYUXcK
      V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVNXVmluMmoyRDI4ZmNaem9jQXlFKzRP
      Z0M0T2ZQZwpQck1HZml4eGtHaFV2dDdGWTQxczJ2RDdzU01VSkhEclhIampUV1lFL3p4M2lYb3ZG
      TGdXMjFmZG80SUJGVENDCkFSRXdEZ1lEVlIwUEFRSC9CQVFEQWdlQU1Bd0dBMVVkRXdFQi93UUNN
      QUF3SFFZRFZSME9CQllFRlAyQkhDZnMKNERPcDZxTERNQ05GWFpHZWlpK21NQjhHQTFVZEl3UVlN
      QmFBRlBTdk91WjRuNkg5ZG1uVHpzQUdxQ3lmQUFLbApNQ1FHQTFVZEVRUWRNQnVDR1dOaExYUnZi
      Mnh6TFRVMFpHWTJaR05rTjJZdGNHWjZlblF3Z1lvR0NDb0RCQVVHCkJ3Z0JCSDU3SW1GMGRISnpJ
      anA3SW1GaVlXTXVhVzVwZENJNkluUnlkV1VpTENKaFpHMXBiaUk2SW5SeWRXVWkKTENKb1ppNUJa
      bVpwYkdsaGRHbHZiaUk2SW5SeVlXUmxjaUlzSW1obUxrVnVjbTlzYkcxbGJuUkpSQ0k2SWtGawpi
      V2x1UUhSeVlXUmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZV1J0YVc0aWZYMHdDZ1lJS29aSXpq
      MEVBd0lEClJ3QXdSQUlnTjZlZHgxRzF0YXBGemRMSjBidnVYejh0ZTFaUXUxSzM0ekE3RUM3dmJN
      NENJRS9iM3V1R1p3YTAKd1hkeXd4SXI4M0VLVXQ4SjVrOC8zaGhQQjFCZzB2akoKLS0tLS1FTkQg
      Q0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2SuEFLS0tLS1CRUdJTiBDRVJUSUZJQ0FU
      RS0tLS0tCk1JSUI5RENDQVpxZ0F3SUJBZ0lVS1BTWG1JOFh1SEJ6RGVUaTdXTTJ0dE5RYmpNd0Nn
      WUlLb1pJemowRUF3SXcKV0RFTE1Ba0dBMVVFQmhNQ1EwZ3hEekFOQmdOVkJBZ01CbHAxY21samFE
      RVBNQTBHQTFVRUJ3d0dXblZ5YVdObwpNUTh3RFFZRFZRUUtEQVpVY21Ga1pYSXhGakFVQmdOVkJB
      TU1EV05oTG5SeVlXUmxjaTF1WlhRd0hoY05Nakl3Ck56SXlNVEUwT0RVMFdoY05NalV3TlRFeE1U
      RTBPRFUwV2pCWU1Rc3dDUVlEVlFRR0V3SkRTREVQTUEwR0ExVUUKQ0F3R1duVnlhV05vTVE4d0RR
      WURWUVFIREFaYWRYSnBZMmd4RHpBTkJnTlZCQW9NQmxSeVlXUmxjakVXTUJRRwpBMVVFQXd3Tlky
      RXVkSEpoWkdWeUxXNWxkREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTDFUCkZF
      MW0wRGpzT3YydkU1OXQvQzhCTWhKVnNvUE1mdGZyV2tWM2RCWnhLVHArQ1VsSm5JSGc1aFdoZkRx
      R3JORTQKMmFZMjArTVNVdFVER2ZnZUNlS2pRakJBTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZ
      RFZSMFBBUUgvQkFRRApBZ0dtTUIwR0ExVWREZ1FXQkJUMHJ6cm1lSitoL1hacDA4N0FCcWdzbndB
      Q3BUQUtCZ2dxaGtqT1BRUURBZ05JCkFEQkZBaUVBMy9uMnRrZEo0NVRmc21xcFREUzZGaVZsVnFJ
      UnhUekI3ZUxiSHRiOGU2SUNJSFVPMCt0cGZ5aWUKUTg3aHl3d08rVHc4WVVaeFZrbDA4RGx0OGNl
      YlBITTYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoaBkFkbWlucyIyCgdSZWFkZXJzEicSHQgB
      EhkSCBIGCAESAggAGg0SCwoJdHJhZGVyTVNQGgZBZG1pbnMiMgoHV3JpdGVycxInEh0IARIZEggS
      BggBEgIIABoNEgsKCXRyYWRlck1TUBoGQWRtaW5zIjMKBkFkbWlucxIpEh8IARIbEggSBggBEgII
      ABoPEg0KCXRyYWRlck1TUBABGgZBZG1pbnMiNgoLRW5kb3JzZW1lbnQSJxIdCAESGRIIEgYIARIC
      CAAaDRILCgl0cmFkZXJNU1AaBkFkbWlucyoGQWRtaW5zEsgWCgtwcm9kdWNlck1TUBK4FhrQFAoD
      TVNQEsgUEr0UEroUCgtwcm9kdWNlck1TUBLtBS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpN
      SUlCL1RDQ0FhS2dBd0lCQWdJVUpFTkkxZEdydXMzRVBIR1VFWW16TmpqNzZ3UXdDZ1lJS29aSXpq
      MEVBd0l3ClhERUxNQWtHQTFVRUJoTUNSMEl4RHpBTkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXUKTVJFd0R3WURWUVFLREFoUWNtOWtkV05sY2pFWU1CWUdBMVVFQXd3UFky
      RXVjSEp2WkhWalpYSXRibVYwTUI0WApEVEl5TURjeU1qRXhOVEExTjFvWERUSTFNRFV4TVRFeE5U
      QTFOMW93WERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOCkJnTlZCQWdNQmt4dmJtUnZiakVQTUEwR0Ex
      VUVCd3dHVEc5dVpHOXVNUkV3RHdZRFZRUUtEQWhRY205a2RXTmwKY2pFWU1CWUdBMVVFQXd3UFky
      RXVjSEp2WkhWalpYSXRibVYwTUZrd0V3WUhLb1pJemowQ0FRWUlLb1pJemowRApBUWNEUWdBRTRo
      cFN1MjBQUzYwTGt1bDBaQTNZS0RibTRzU2xSVFJPVDg5em53NXBZK2JrNVVWcE8zQjVpY3FYCmtN
      MGttS0RLdGpQWmVnZk14aVJGTkZod3VJQk9MYU5DTUVBd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pB
      T0JnTlYKSFE4QkFmOEVCQU1DQWFZd0hRWURWUjBPQkJZRUZEVUNUb1poeXBvYTR4OVNWRDFSOTBK
      TzgvS0VNQW9HQ0NxRwpTTTQ5QkFNQ0Ewa0FNRVlDSVFEWnkvM1VDSE0xZjhoa05oNUU1VEYxSGJx
      TGdObHppS2drelptU01XVndBUUloCkFOREpDU0x0aWltejRNbzd1VG9rV2dDSjE4d2FpUEJtNXZ6
      d24rNzM3UTBmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KIroILS0tLS1CRUdJTiBDRVJUSUZJ
      Q0FURS0tLS0tCk1JSUM4ekNDQXBxZ0F3SUJBZ0lVVUN3T2c2Y1VySlRFSjJHWGo1NlRLc0dGd0Iw
      d0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhEekFOQmdOVkJBZ01Ca3h2Ym1S
      dmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtEQWhRY205a2RXTmxjakVZTUJZ
      R0ExVUVBd3dQWTJFdWNISnZaSFZqWlhJdGJtVjBNQjRYCkRUSXlNRGN5TWpFeU1ERXdNRm9YRFRJ
      ek1EY3lNakV5TURZd01Gb3dlekVMTUFrR0ExVUVCaE1DUjBJeEd6QVoKQmdOVkJBY1RFalV4TGpV
      d0x5MHdMakV6TDB4dmJtUnZiakVSTUE4R0ExVUVDaE1JVUhKdlpIVmpaWEl4SHpBTQpCZ05WQkFz
      VEJXRmtiV2x1TUE4R0ExVUVDeE1JY0hKdlpIVmpaWEl4R3pBWkJnTlZCQU1NRWtGa2JXbHVRSEJ5
      CmIyUjFZMlZ5TFc1bGREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJQa3RvblVn
      ZHJKNVUzZ2YKKzM0Z2dYSExqaGtvczZsbk5tME5rWENnNjVpTkUveDFpdVVTeXluM0ZvQkNBZ0ph
      TFo0SmYxaEhKdTNrM1JSZwp3dUpkZnZ5amdnRVpNSUlCRlRBT0JnTlZIUThCQWY4RUJBTUNCNEF3
      REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WCkhRNEVGZ1FVd0ZtQzI4K1Fza3FQb0JrRzlYdG1qU2kw
      dW53d0h3WURWUjBqQkJnd0ZvQVVOUUpPaG1IS21ocmoKSDFKVVBWSDNRazd6OG9Rd0l3WURWUjBS
      QkJ3d0dvSVlZMkV0ZEc5dmJITXRZbUptTm1JMFl6ZG1MWGM0T1hjNQpNSUdQQmdncUF3UUZCZ2NJ
      QVFTQmduc2lZWFIwY25NaU9uc2lZV0poWXk1cGJtbDBJam9pZEhKMVpTSXNJbUZrCmJXbHVJam9p
      ZEhKMVpTSXNJbWhtTGtGbVptbHNhV0YwYVc5dUlqb2ljSEp2WkhWalpYSWlMQ0pvWmk1RmJuSnYK
      Ykd4dFpXNTBTVVFpT2lKQlpHMXBia0J3Y205a2RXTmxjaTF1WlhRaUxDSm9aaTVVZVhCbElqb2lZ
      V1J0YVc0aQpmWDB3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnTFJSZzhQWEZwTmFJdEZDRHF5VE5N
      TkF6ZEU5TmZJYTRjWXlUCjc3Q201c29DSUZwc0FCY2VnOEd4STdZUmNNZmtEUjVyZGZTRjYrU1p3
      ckxLVDlpTHJhN3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQpCDgoEU0hBMhIGU0hBMjU2Su0F
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUIvVENDQWFLZ0F3SUJBZ0lVSkVOSTFkR3J1
      czNFUEhHVUVZbXpOamo3NndRd0NnWUlLb1pJemowRUF3SXcKWERFTE1Ba0dBMVVFQmhNQ1IwSXhE
      ekFOQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dQpNUkV3RHdZRFZRUUtE
      QWhRY205a2RXTmxjakVZTUJZR0ExVUVBd3dQWTJFdWNISnZaSFZqWlhJdGJtVjBNQjRYCkRUSXlN
      RGN5TWpFeE5UQTFOMW9YRFRJMU1EVXhNVEV4TlRBMU4xb3dYREVMTUFrR0ExVUVCaE1DUjBJeER6
      QU4KQmdOVkJBZ01Ca3h2Ym1SdmJqRVBNQTBHQTFVRUJ3d0dURzl1Wkc5dU1SRXdEd1lEVlFRS0RB
      aFFjbTlrZFdObApjakVZTUJZR0ExVUVBd3dQWTJFdWNISnZaSFZqWlhJdGJtVjBNRmt3RXdZSEtv
      Wkl6ajBDQVFZSUtvWkl6ajBECkFRY0RRZ0FFNGhwU3UyMFBTNjBMa3VsMFpBM1lLRGJtNHNTbFJU
      Uk9UODl6bnc1cFkrYms1VVZwTzNCNWljcVgKa00wa21LREt0alBaZWdmTXhpUkZORmh3dUlCT0xh
      TkNNRUF3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFPQmdOVgpIUThCQWY4RUJBTUNBYVl3SFFZRFZS
      ME9CQllFRkRVQ1RvWmh5cG9hNHg5U1ZEMVI5MEpPOC9LRU1Bb0dDQ3FHClNNNDlCQU1DQTBrQU1F
      WUNJUURaeS8zVUNITTFmOGhrTmg1RTVURjFIYnFMZ05semlLZ2t6Wm1TTVdWd0FRSWgKQU5ESkNT
      THRpaW16NE1vN3VUb2tXZ0NKMTh3YWlQQm01dnp3bis3MzdRMGYKLS0tLS1FTkQgQ0VSVElGSUNB
      VEUtLS0tLQoaBkFkbWlucyI0CgdSZWFkZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLcHJvZHVj
      ZXJNU1AaBkFkbWlucyI0CgdXcml0ZXJzEikSHwgBEhsSCBIGCAESAggAGg8SDQoLcHJvZHVjZXJN
      U1AaBkFkbWlucyI1CgZBZG1pbnMSKxIhCAESHRIIEgYIARICCAAaERIPCgtwcm9kdWNlck1TUBAB
      GgZBZG1pbnMiOAoLRW5kb3JzZW1lbnQSKRIfCAESGxIIEgYIARICCAAaDxINCgtwcm9kdWNlck1T
      UBoGQWRtaW5zKgZBZG1pbnMaQAoVQ2hhbm5lbENyZWF0aW9uUG9saWN5EicSDAgDEggKBkFkbWlu
      cxoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVyZXIvQWRtaW5zIi0KBkFk
      bWlucxIjEggIARIEEgISABoXL0NoYW5uZWwvT3JkZXJlci9BZG1pbnMqFy9DaGFubmVsL09yZGVy
      ZXIvQWRtaW5zGiYKEEhhc2hpbmdBbGdvcml0aG0SEhIICgZTSEEyNTYaBkFkbWlucxotChlCbG9j
      a0RhdGFIYXNoaW5nU3RydWN0dXJlEhASBgj/////DxoGQWRtaW5zGk4KEE9yZGVyZXJBZGRyZXNz
      ZXMSOhIfCh1vcmRlcmVyMS5zdXBwbHljaGFpbi1uZXQ6NzA1MBoXL0NoYW5uZWwvT3JkZXJlci9B
      ZG1pbnMaJAoMQ2FwYWJpbGl0aWVzEhQSCgoICgRWMl8wEgAaBkFkbWlucyIiCgZBZG1pbnMSGBIO
      CAMSCgoGQWRtaW5zEAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlu
      cyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGg4KBAoCCgAKAAoA
      CgAKAA==

    config:
      pod:
        resources:
          limits:
            memory: 512M
            cpu: 1
          requests:
            memory: 512M
            cpu: 0.5
